SELECT SUM(SALES) AS TOTAL_SALES
FROM `CUSTOMERS SALES`;
SELECT SUM(PROFIT) AS TOTAL_PROFIT
FROM `CUSTOMERS SALES`;
SELECT COUNT(DISTINCT`ORDER ID`) AS NUM_OF_ORDERS
FROM `CUSTOMERS SALES`;
select `customer name`, `customer id`, sum(`sales`) as Total_Sales
from `customers sales`
group by `customer name`, `customer id`
order by total_sales DESC
limit 10;
SELECT `CUSTOMER NAME`, SUM(`SALES`) AS TOTAL_SALES
FROM `CUSTOMERS SALES`
GROUP BY `CUSTOMER NAME`
ORDER BY TOTAL_SALES DESC;
select `segment`, round(sum(`sales`), 2) as segment_sales
from `customers sales`
group by `segment`
order by segment_sales desc;
SELECT `CATEGORY`,`SUB-CATEGORY`, ROUND(SUM(`SALES`), 2) AS TOTAL_SALES
FROM `CUSTOMERS SALES`
GROUP BY `CATEGORY`, `SUB-CATEGORY`
ORDER BY TOTAL_SALES DESC;
SELECT `CATEGORY`, ROUND(SUM(`SALES`), 2) as total_sales
from `customers sales`	
group by `category`
order by total_sales desc;
SELECT `CATEGORY`,`SUB-CATEGORY`, ROUND(SUM(`SALES`), 2) AS TOTAL_SALES
FROM `CUSTOMERS SALES`
GROUP BY `CATEGORY`, `SUB-CATEGORY`
ORDER BY TOTAL_SALES ASC;
SELECT `REGION`, ROUND(SUM(`SALES`), 2) AS REGIONAL_SALES
FROM `CUSTOMERS SALES`
GROUP BY `REGION`
ORDER BY REGIONAL_SALES DESC;
SELECT `STATE`, ROUND(SUM(`SALES`), 2) AS SALES_PER_STATE
FROM `CUSTOMERS SALES`
GROUP BY `STATE`
ORDER BY SALES_PER_STATE DESC;
SELECT `City`, ROUND(SUM(`SALES`), 2) AS City_sales
FROM `CUSTOMERS SALES`
GROUP BY `City`
ORDER BY city_sales DESC
Limit 10;
SELECT `CUSTOMER ID`, `CUSTOMER NAME`, `PROFIT`,
CASE
WHEN `PROFIT` > 0 THEN 'PROFITABLE'
ELSE 'LOSS'
END AS PROFIT_DESCRIPTION
FROM `CUSTOMERS SALES`;
SELECT `CUSTOMER NAME`, SUM(`SALES`) AS TOTAL_SALES, DENSE_RANK() OVER (ORDER BY SUM(`SALES`) DESC) AS Rank_number
from `customers sales`
group by `customer name`;